export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#7a7582',
        'outline-variant': '#cbc4d2',
        'on-primary-fixed-variant': '#4f378a',
        'on-primary-fixed': '#22005d',
        tertiary: '#765b00',
        'tertiary-fixed': '#ffdf93',
        'surface-container-high': '#dce9ff',
        'on-primary-container': '#e0d2ff',
        'primary-container': '#6750a4',
        'on-secondary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#503d00',
        'surface-variant': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'on-surface': '#0b1c30',
        primary: '#4f378a',
        'on-secondary-fixed-variant': '#4b4263',
        'surface-dim': '#cbdbf5',
        'on-background': '#0b1c30',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d3e4fe',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#241a00',
        'on-secondary-container': '#645a7d',
        'on-secondary-fixed': '#1f1635',
        'on-error': '#ffffff',
        'inverse-surface': '#213145',
        primaryfixed: '#e9ddff',
        surface: '#f8f9ff',
        'secondary-fixed-dim': '#cdc0e9',
        'on-surface-variant': '#494551',
        'primary-fixed-dim': '#cfbcff',
        background: '#f8f9ff',
        'on-error-container': '#93000a',
        'secondary-container': '#e1d4fd',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#cfbcff',
        'surface-tint': '#6750a4',
        'on-tertiary-fixed-variant': '#594400',
        'tertiary-container': '#c9a74d',
        'surface-container': '#e5eeff',
        'tertiary-fixed-dim': '#e7c365',
        'surface-bright': '#f8f9ff',
        error: '#ba1a1a',
        secondary: '#63597c',
        'secondary-fixed': '#e9ddff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        unit: '8px',
        gutter: '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'display-lg': ['Inter'],
        'title-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}